import type { EventItem, UserProfile } from '../types';

function getRelativeDate(daysOffset: number, startHour: number, endHour: number): { start: string; end: string } {
  const start = new Date();
  start.setDate(start.getDate() + daysOffset);
  start.setHours(startHour, 0, 0, 0);

  const end = new Date(start);
  if (endHour < startHour) {
    end.setDate(end.getDate() + 1);
  }
  end.setHours(endHour, 0, 0, 0);

  return {
    start: start.toISOString(),
    end: end.toISOString(),
  };
}

export const KNOWN_ORGANIZER_EMAILS: string[] = [];

export const isAuthorizedOrganizer = (_email?: string): boolean => {
  return false;
};

export const MOCK_ORGANIZERS: UserProfile[] = [];

export const MOCK_ADMIN: UserProfile = {
  id: 'admin-jesus',
  email: 'jesushidalgo25@gmail.com',
  full_name: 'Jesús Hidalgo (Admin)',
  role: 'admin',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  bio: 'Administrador general y moderador oficial de Sale Baile.',
  created_at: '2026-01-01T00:00:00Z',
};

const today = new Date();
const daysToFri = ((5 - today.getDay() + 7) % 7) || 7;
const dateFri = getRelativeDate(daysToFri, 22, 5); // Próximo Viernes 22:00 a 05:00
const dateSat = getRelativeDate(daysToFri + 1, 21, 5); // Próximo Sábado 21:30 a 05:00

export const INITIAL_MOCK_EVENTS: EventItem[] = [
  {
    id: 'evt-bachataroom-palermo',
    organizer_id: 'admin-jesus',
    title: 'Gran Social Bachata Room en Palermo',
    description: 'Increíble noche de Bachata Sensual en Palermo. Clases abiertas a las 22:00 hs con profesores invitados de primer nivel y pista abierta con el mejor DJ de Bachata hasta las 05:00 hs.',
    flyer_url: '/flyers/flyer_bachata_azuquita.jpg',
    flyer_aspect_ratio: 0.75,
    category: 'social',
    genre_family: 'bachata',
    subgenres: ['bachata-sensual', 'bachata-dominicana'],
    start_time: dateFri.start,
    end_time: dateFri.end,
    timezone: 'America/Argentina/Buenos_Aires',
    venue_name: 'Bachata Room Club Palermo',
    address: 'Av. Santa Fe 2534',
    city: 'Buenos Aires (Palermo)',
    province: 'Capital Federal',
    country: 'Argentina',
    latitude: -34.5880,
    longitude: -58.4150,
    is_free: false,
    price: 6000,
    advance_ticket_price: 4500,
    admin_resale_price: 3600,
    admin_commission_rate: '900 ARS (20%)',
    currency: 'ARS',
    advance_tickets_whatsapp: '+5491155551234',
    organizer_name: 'Bachata Room Buenos Aires',
    organizer_whatsapp: '+5491155551234',
    organizer_instagram: '@bachataroom.ba',
    rating_average: 5.0,
    rating_count: 14,
    is_featured: true,
    status: 'publicado',
    is_cancelled: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'evt-azuquita-flores',
    organizer_id: 'admin-jesus',
    title: 'Azuquita Bachata & Salsa Social Club',
    description: 'La gran fiesta de Flores con lo mejor de la bachata y la salsa. Clases grupales, pista climatizada y 2 DJs en vivo.',
    flyer_url: '/flyers/flyer_bachata_merlo.jpg',
    flyer_aspect_ratio: 0.75,
    category: 'social',
    genre_family: 'salsa-y-bachata',
    subgenres: ['social-salsa-bachata', 'matine-salsa-bachata'],
    start_time: dateSat.start,
    end_time: dateSat.end,
    timezone: 'America/Argentina/Buenos_Aires',
    venue_name: 'Azuquita Social Club',
    address: 'Av. Rivadavia 8500',
    city: 'Buenos Aires (Flores)',
    province: 'Capital Federal',
    country: 'Argentina',
    latitude: -34.6300,
    longitude: -58.4750,
    is_free: false,
    price: 6500,
    advance_ticket_price: 5000,
    admin_resale_price: 4000,
    admin_commission_rate: '1000 ARS (20%)',
    currency: 'ARS',
    advance_tickets_whatsapp: '+5491155551234',
    organizer_name: 'Azuquita Bachata',
    organizer_whatsapp: '+5491155551234',
    organizer_instagram: '@azuquitabachata',
    rating_average: 4.9,
    rating_count: 8,
    is_featured: true,
    status: 'publicado',
    is_cancelled: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'evt-sensual-palermo',
    organizer_id: 'admin-jesus',
    title: 'Sensual Bachata Night & Workshop Especial',
    description: 'Masterclass intensiva con campeones nacionales y baile social con shows en vivo hasta el amanecer.',
    flyer_url: '/flyers/flyer_prueba_organizador.jpg',
    flyer_aspect_ratio: 0.75,
    category: 'taller',
    genre_family: 'bachata',
    subgenres: ['bachata-sensual'],
    start_time: dateFri.start,
    end_time: dateFri.end,
    timezone: 'America/Argentina/Buenos_Aires',
    venue_name: 'Club Sensual BA',
    address: 'Gorriti 5500',
    city: 'Buenos Aires (Palermo)',
    province: 'Capital Federal',
    country: 'Argentina',
    latitude: -34.5850,
    longitude: -58.4350,
    is_free: false,
    price: 5500,
    advance_ticket_price: 4000,
    admin_resale_price: 3200,
    admin_commission_rate: '800 ARS (20%)',
    currency: 'ARS',
    advance_tickets_whatsapp: '+5491155551234',
    organizer_name: 'Sensual Bachata BA',
    organizer_whatsapp: '+5491155551234',
    organizer_instagram: '@sensualbachataba',
    rating_average: 4.8,
    rating_count: 6,
    is_featured: false,
    status: 'publicado',
    is_cancelled: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'evt-salsa-cubana-san-telmo',
    organizer_id: 'admin-rodwil',
    title: 'Noche de Timba & Salsa Cubana',
    description: 'Rueda de Casino, taller de son cubano y pista encendida con la mejor timba y salsa cubana de San Telmo.',
    flyer_url: '/flyers/flyer_bachata_azuquita.jpg',
    flyer_aspect_ratio: 0.75,
    category: 'social',
    genre_family: 'salsa',
    subgenres: ['salsa-cubana', 'salsa-linea'],
    start_time: dateSat.start,
    end_time: dateSat.end,
    timezone: 'America/Argentina/Buenos_Aires',
    venue_name: 'La Casona de San Telmo',
    address: 'Defensa 840',
    city: 'Buenos Aires (San Telmo)',
    province: 'Capital Federal',
    country: 'Argentina',
    latitude: -34.6180,
    longitude: -58.3720,
    is_free: false,
    price: 6000,
    advance_ticket_price: 4500,
    currency: 'ARS',
    organizer_name: 'Timba & Son',
    organizer_instagram: '@timbayson_ba',
    rating_average: 5.0,
    rating_count: 9,
    is_featured: false,
    status: 'publicado',
    is_cancelled: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'evt-rockabilly-almagro',
    organizer_id: 'admin-rodwil',
    title: 'Rock & Roll 50s Social Dance',
    description: 'Pista de madera para bailar Rock and Roll clásico, Rockabilly y Swing. Banda en vivo y clases para principiantes.',
    flyer_url: '/flyers/flyer_bachata_merlo.jpg',
    flyer_aspect_ratio: 0.75,
    category: 'social',
    genre_family: 'rock',
    subgenres: ['rock-and-roll', 'rockabilly', 'swing'],
    start_time: dateFri.start,
    end_time: dateFri.end,
    timezone: 'America/Argentina/Buenos_Aires',
    venue_name: 'Salón Boedo Rock',
    address: 'Av. Boedo 950',
    city: 'Buenos Aires (Almagro / Boedo)',
    province: 'Capital Federal',
    country: 'Argentina',
    latitude: -34.6280,
    longitude: -58.4180,
    is_free: false,
    price: 5000,
    advance_ticket_price: 4000,
    currency: 'ARS',
    organizer_name: 'Rockabilly Club BA',
    organizer_instagram: '@rockabillyclub_ba',
    rating_average: 4.9,
    rating_count: 12,
    is_featured: false,
    status: 'publicado',
    is_cancelled: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'evt-melani-jose-c-paz',
    organizer_id: 'admin-jesus',
    title: 'Melani Social Bachata & Salsa',
    description: 'La gran fiesta de José C. Paz en Melani. Pista climatizada, clases especiales de bachata y salsa, y el mejor ambiente hasta el amanecer.',
    flyer_url: '/flyers/flyer_bachata_merlo.jpg',
    flyer_aspect_ratio: 0.75,
    category: 'social',
    genre_family: 'bachata',
    subgenres: ['bachata-sensual', 'bachata-dominicana'],
    start_time: dateSat.start,
    end_time: dateSat.end,
    timezone: 'America/Argentina/Buenos_Aires',
    venue_name: 'Melani',
    address: 'Av. Presidente Hipólito Yrigoyen 2400',
    city: 'José C. Paz',
    province: 'Buenos Aires',
    country: 'Argentina',
    latitude: -34.5154,
    longitude: -58.7681,
    is_free: false,
    price: 8000,
    currency: 'ARS',
    organizer_name: 'Melani (@melanybys)',
    organizer_instagram: '@melanybys',
    rating_average: 5.0,
    rating_count: 18,
    is_featured: true,
    status: 'publicado',
    is_cancelled: false,
    created_at: new Date().toISOString(),
  }
];

export const INITIAL_MOCK_REVIEWS: any[] = [];

export const INITIAL_MOCK_PROMOTERS: any[] = [];
